
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_ledger
    username: wallet_user
    password: wallet_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
