  name: CI

  on:
    push:
      branches: [ "**" ]
    pull_request:
      branches: [ "**" ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Build commons JAR
          run: mvn clean install -DskipTests -f common/pom.xml

        - name: Build ledger-service
          run: mvn clean install -DskipTests -f ledger-service/pom.xml

        - name: Build with Maven
          run: mvn -B clean verify -DskipTests
